# yaml file to configure readthedocs build
version: 2
build:
    os: ubuntu-22.04
    tools:
        python: "3.12"
sphinx:
    configuration: docs/conf.py
    # disable this for more lenient docs builds
    fail_on_warning: false
python:
    install:
        - method: pip
          path: .
          extra_requirements:
              - doc
        - requirements: docs/requirements.txt
