name: sincei
channels:
 - bioconda
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - scanpy
 - deeptools
 - pip
 - pip:
   - gensim
   - "--editable=git+ssh://git@github.com:vivekbhr/sincei.git@master#egg=sincei"
