name: pypi
on: [push]
jobs:
  pypi:
    name: upload to pypi
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        auto-activate-base: false
    - name: Create env
      run: |
        mamba create -n upload -q --yes python=3.8 twine
    - name: sdist
      run: |
        mamba activate upload
        mamba info
        rm -f dist/*
        python setup.py sdist
    - name: upload
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      env:
        TWINE_USERNAME: ${{ secrets.pypi_username }}
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        twine upload dist/*
