name: pypi
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pypi:
    name: upload to pypi
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
    - name: Create env
      run: |
        conda create -n upload -c conda-forge -q --yes python=3.8 twine hatch
    - name: sdist
      run: |
        conda activate upload
        conda info
        rm -f dist/*
        hatch build -t sdist
    - name: upload
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
